### ISSUE TITLE
Random bug

### ISSUE THREAD

**Issue by manuel465** [xtingray/tupitube.desk#7]
" "[New LWP 8943]<p></p> [New LWP 8944]<p></p> [Thread debugging using libthread_db enabled]<p></p> Using host libthread_db library "/lib64/libthread_db.so.1". 0x00007f584b610b57 in waitpid () from /lib64/libpthread.so.0 <p></p>#0 0x00007f584b610b57 in waitpid () at /lib64/libpthread.so.0 <p></p>#1 0x000000000043b4b1 in crashTrapper(int) (sig=6) at tupcrashhandler.cpp:321 <p></p>#2 0x00007f584a990130 in <signal handler called> () at /lib64/libc.so.6 <p></p>#3 0x00007f584a9900b0 in raise () at /lib64/libc.so.6 <p></p>#4 0x00007f584a991691 in abort () at /lib64/libc.so.6 <p></p>#5 0x00007f584bb33dcc in qErrnoWarning(char const*, ...) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Core.so.5 <p></p>#6 0x00007f584bb33514 in (anonymous namespace)::Q_QGS_qMessagePattern::innerFunction()::HolderBase::~HolderBase() [clone .isra.26]<p></p> () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Core.so.5 <p></p>#7 0x00007f582fbc2d29 in QList<TPushButton*>::at(int) const (this=0x2f784f40, i=4) at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/include/QtCore/qlist.h:544 <p></p>#8 0x00007f582fbbfd78 in StepsViewer::addTableRow(int, int) (this=0x3104750, row=4, frames=4) at stepsviewer.cpp:525 <p></p>#9 0x00007f582fbbdf67 in StepsViewer::setPath(QGraphicsPathItem const*) (this=0x3104750, pathItem=0x3104ce40) at stepsviewer.cpp:200 <p></p>#10 0x00007f582e493f7b in Settings::updateSteps(QGraphicsPathItem const*) (this=0x2fb40130, path=0x3104ce40) at settings.cpp:214 <p></p>#11 0x00007f582e491d8d in Configurator::updateSteps(QGraphicsPathItem const*) (this=0x2fb7b2d0, path=0x3104ce40) at configurator.cpp:195 <p></p>#12 0x00007f582e48a2b6 in Tweener::updatePath() (this=0x2fa8d80) at tweener.cpp:853 <p></p>#13 0x00007f582e49574c in Tweener::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x2fa8d80, _c=QMetaObject::InvokeMetaMethod, _id=11, _a=0x7ffe1e885bd0) at .moc/moc_tweener.cpp:129 <p></p>#14 0x00007f584bd4c989 in QMetaObject::activate(QObject*, int, int, void**) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Core.so.5 <p></p>#15 0x00007f5851421ba5 in TNodeGroup::nodeReleased() (this=0x2cf27a0) at moc_tnodegroup.cpp:178 <p></p>#16 0x00007f5851401e3d in TNodeGroup::emitNodeClicked(TControlNode::State) (this=0x2cf27a0, state=TControlNode::Released) at tnodegroup.cpp:315 <p></p>#17 0x00007f58513ee37d in TControlNode::mouseReleaseEvent(QGraphicsSceneMouseEvent*) (this=0x2d557ab0, event=0x7ffe1e886180) at tcontrolnode.cpp:219 <p></p>#18 0x00007f584d77ab78 in QGraphicsItem::sceneEvent(QEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#19 0x00007f584d79dbac in QGraphicsScenePrivate::sendMouseEvent(QGraphicsSceneMouseEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#20 0x00007f584d7a324a in QGraphicsScene::mouseReleaseEvent(QGraphicsSceneMouseEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#21 0x00007f584eec4beb in TupGraphicsScene::mouseReleaseEvent(QGraphicsSceneMouseEvent*) (this=0x2d513a10, event=0x7ffe1e886180) at tupgraphicsscene.cpp:1372 <p></p>#22 0x00007f584d7ae190 in QGraphicsScene::event(QEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#23 0x00007f584eec4f41 in TupGraphicsScene::event(QEvent*) (this=0x2d513a10, event=0x7ffe1e886180) at tupgraphicsscene.cpp:1520 <p></p>#24 0x00007f584d4b46fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#25 0x00007f584d4bb7f0 in QApplication::notify(QObject*, QEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#26 0x00007f584bd20e98 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Core.so.5 <p></p>#27 0x00007f584d7ca62c in QGraphicsView::mouseReleaseEvent(QMouseEvent*) () at /home/xtingray/Qt5.12.2/5.12.2/gcc_64/lib/libQt5Widgets.so.5 <p></p>#28 0x00007f584eeba6c7 in TupPaintAreaBase::mouseReleaseEvent(QMouseEvent*) (this=0x26086c00, event=0x7ffe1e8866d0)

**Comment by manuel465** [comment]
Cerrado por que el problema va anidado a una descripcion
